[package]
name = "irc_bot"
version = "0.1.0"
authors = ["Dylan Abraham <dylan.abraham22@gmail.com>"]

[dependencies]
irc = "0.13.5"
regex = "1"
lazy_static = "0.2"
dynamic_reload = "0.3.0"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
env_logger = "0.5"